rules:
  unpinned-uses:
    ignore:
      - code-scan.yml:12
      - goreleaser.yml:133
      - goreleaser.yml:141
  excessive-permissions:
    ignore:
      - ci.yml:1
      - ci.yml:19
      - ci.yml:35
      - code-scan.yml:10
      - goCI.yml:97
      - goCI.yml:111
      - goCI.yml:121
      - goCI.yml:133
      - goCI.yml:158
      - sync-winget-fork.yml:9
