name: Lint GitHub Actions workflows
on:
  workflow_call:

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint GitHub workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check workflow files
        uses: docker://index.docker.io/rhysd/actionlint@sha256:6f03470d0152251d7f07f7c4dc019dbe7024c72cd952f839544c7798843efa8f # 1.7.11
        with:
          args: -color
