on:
  workflow_call:
    inputs:
      run-codeql:
        required: false
        type: boolean
        default: true

jobs:
  codeql:
    if: inputs.run-codeql
    uses: smallstep/workflows/.github/workflows/codeql-analysis.yml@main
