on:
  workflow_call:
    inputs:
      run-codeql:
        required: false
        type: boolean
        default: true
      runs-on:
        required: false
        type: string
        default: ''
      codeql-build-cmd:
        required: false
        type: string
        default: 'V=1 make build'
      codeql-build-mode:
        required: false
        type: string
        default: ''
      codeql-runs-on:
        required: false
        type: string
        default: ''
      os-dependencies:
        required: false
        type: string
        default: ''
      codeql-os-dependencies:
        required: false
        type: string
        default: ''

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql:
    if: inputs.run-codeql
    uses: ./.github/workflows/codeql-analysis.yml
    with:
      runs-on: ${{ inputs.codeql-runs-on || inputs.runs-on || 'ubuntu-latest' }}
      build-cmd: ${{ inputs.codeql-build-cmd }}
      build-mode: ${{ inputs.codeql-build-mode }}
      os-dependencies: ${{ inputs.codeql-os-dependencies || inputs.os-dependencies || '' }}
