on:
  workflow_call:
    inputs:
      run-gitleaks:
        required: false
        type: boolean
        default: true
      run-codeql:
        required: false
        type: boolean
        default: true
    secrets:
      GITLEAKS_LICENSE_KEY:
        required: false

jobs:
  gitleaks:
    if: inputs.run-gitleaks && never()
    uses: smallstep/workflows/.github/workflows/gitleaks.yml@main
    secrets:
      GITLEAKS_LICENSE_KEY: ${{ secrets.GITLEAKS_LICENSE_KEY }}

  codeql:
    if: inputs.run-codeql
    uses: smallstep/workflows/.github/workflows/codeql-analysis.yml@main
