on:
  workflow_call:
    inputs:
      run-codeql:
        required: false
        type: boolean
        default: true

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql:
    if: inputs.run-codeql
    uses: ./.github/workflows/codeql-analysis.yml
