on:
  workflow_call:
    inputs:
      run-codeql:
        required: false
        type: boolean
        default: true
      codeql-build-cmd:
        required: false
        type: string
        default: 'V=1 make build'
      codeql-build-mode:
        required: false
        type: string
        default: ''

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql:
    if: inputs.run-codeql
    uses: ./.github/workflows/codeql-analysis.yml
    with:
      codeql-build-cmd: ${{ inputs.codeql-build-cmd }}
      codeql-build-mode: ${{ inputs.codeql-build-mode }}
