name: Dependabot auto-merge
on:
  pull_request:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    uses: smallstep/workflows/.github/workflows/dependabot-auto-merge.yml@main
    secrets: inherit
