on:
  workflow_call:
    secrets:
      GITLEAKS_LICENSE_KEY:
        required: true
      PAT:
        required: false

jobs:
  gitleaks:
    if: false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      GOPRIVATE: go.step.sm
    steps:
      - name: Setup SSH key for private dependencies
        uses: webfactory/ssh-agent@v0.5.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout w/ PAT
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: Checkout w/out PAT
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT == '' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Reconfigure Git for HTTP Auth
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        run: |
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf git+ssh://git@github.com
      - name: Configure GitLeaks
        if:  hashFiles('.gitleaks.toml') == ''
        run: |
          curl -O https://raw.githubusercontent.com/smallstep/workflows/master/.gitleaks.toml
      - name: gitleaks w/ PAT
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}
          GITLEAKS_ENABLE_COMMENTS: true
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}
          GITLEAKS_ENABLE_COMMENTS: true
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT == '' }}
      - uses: github/codeql-action/upload-sarif@v2
        if: always() && hashFiles('results.sarif') != ''
        with:
          sarif_file: results.sarif

