on:
  workflow_call:
    inputs:
      build-command:
        required: false
        type: string
        default: 'V=1 make build'
      os-dependencies:
        required: false
        type: string
      only-latest-golang:
        required: false
        type: boolean
        default: true
      goprivate:
        required: false
        type: string
        default: go.step.sm,github.com/smallstep
    secrets:
      PAT:
        required: false

jobs:
  set-go-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-output.outputs.matrix }}
    steps:
      - name: Set go-matrix latest version
        id: set-matrix-latest
        if: inputs.only-latest-golang
        run: |
          echo 'matrix={"include":[{"go":"\"stable\""}]}' >> "${GITHUB_ENV}"
      - name: Set default go-matrix
        id: set-matrix-default
        if: inputs.only-latest-golang == false
        run: |
          echo 'matrix={"include":[{"go":"\"stable\""},{"go":"\"oldstable\""}]}' >> "${GITHUB_ENV}"
      - id: set-output
        run: |
          echo "matrix=${{ env.matrix }}" >> "${GITHUB_OUTPUT}"

  build:
    needs: set-go-matrix
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    strategy:
      matrix: ${{ fromJson(needs.set-go-matrix.outputs.matrix) }}
    steps:
      - name: Install Dependencies # Some dependencies require this package
        if: ${{ inputs.os-dependencies != '' }}
        run: |
          sudo apt-get install ${{ inputs.os-dependencies }}
      - name: Checkout w/ PAT
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        with:
          submodules: true
          token: ${{ secrets.PAT }}
      - name: Checkout w/out PAT
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT == '' }}
        with:
          submodules: true
      - name: Reconfigure Git for go.step.sm
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        run: |
          git config --global --add url."https://${{ secrets.PAT }}@github.com/smallstep/".insteadOf https://github.com/smallstep/
          git config --global --add url."https://${{ secrets.PAT }}@github.com/smallstep/".insteadOf git+ssh://git@github.com/smallstep/
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true
      - name: Build
        run: ${{ inputs.build-command }}
