on:
  workflow_call:
    inputs:
      build-command:
        required: false
        type: string
        default: 'V=1 make build'
      os-dependencies:
        required: false
        type: string
      only-latest-golang:
        required: false
        type: boolean
        default: false
      goprivate:
        required: false
        type: string
        default: go.step.sm
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      PAT:
        required: false

jobs:
  set-go-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-output.outputs.matrix }}
    steps:
      - name: Set go-matrix latest version
        id: set-matrix-latest
        if: inputs.only-latest-golang
        run: |
          echo 'matrix={"include":[{"go":"\"stable\""}]}' >> ${GITHUB_ENV}
      - name: Set default go-matrix
        id: set-matrix-default
        if: inputs.only-latest-golang == false
        run: |
          echo 'matrix={"include":[{"go":"\"stable\""},{"go":"\"oldstable\""}]}' >> ${GITHUB_ENV}
      - id: set-output
        run: |
          echo "matrix=${{ env.matrix }}" >> ${GITHUB_OUTPUT}

  build:
    needs: set-go-matrix
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    strategy:
      matrix: ${{ fromJson(needs.set-go-matrix.outputs.matrix) }}
    steps:
      - name: Install Dependencies # Some dependencies require this package
        if: ${{ inputs.os-dependencies != '' }}
        run: |
          sudo apt-get install ${{ inputs.os-dependencies }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Reconfigure Git for go.step.sm
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        run: |
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf git+ssh://git@github.com
          git config --global url.git@github.com:.insteadOf https://github.com/
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true
      - name: Setup SSH key for private dependencies
        uses: webfactory/ssh-agent@v0.7.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build
        run: ${{ inputs.build-command }}
