on:
  workflow_call:
    inputs:
      os-dependencies:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      PAT:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: go.step.sm
    strategy:
      matrix:
        go: ['1.18', '1.19']
    steps:
      - name: Install Dependencies # Some dependencies require this package
        if: ${{ inputs.os-dependencies != '' }}
        run: |
          sudo apt-get install ${{ inputs.os-dependencies }}
      - name: Setup SSH key for private dependencies
        uses: webfactory/ssh-agent@v0.5.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout w/ PAT
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true
      - name: Checkout w/out PAT
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT == '' }}
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Reconfigure Git for HTTP Auth
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        run: |
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf git+ssh://git@github.com
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Build
        run: V=1 make build
