on:
  workflow_call:
    inputs:
      cosign-version:
        required: false
        type: string
        default: 'v1.13.1'
      goprivate:
        required: false
        type: string
        default: go.step.sm
      go-version:
        required: false
        type: string
        default: 'stable'
      os-dependencies:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      GORELEASER_PAT:
        required: true
      PAT:
        required: false

jobs:
  goreleaser:
    name: Upload Assets To Github w/ goreleaser
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    steps:
      - name: Install Dependencies # Some dependencies require this package
        if: ${{ inputs.os-dependencies != '' }}
        run: |
          sudo apt-get install ${{ inputs.os-dependencies }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ inputs.go-version }}'
          check-latest: true
      - name: Setup SSH key for private dependencies
        uses: webfactory/ssh-agent@v0.8.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Reconfigure Git for private repos
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        run: |
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf git+ssh://git@github.com
          git config --global url.git@github.com:.insteadOf https://github.com/
      - name: Install cosign
        uses: sigstore/cosign-installer@v2
        with:
          cosign-release: '${{ inputs.cosign-version }}'
      - name: Get Release Date
        id: release_date
        run: |
          RELEASE_DATE=$(date -u +"%y-%m-%d")
          echo "RELEASE_DATE=${RELEASE_DATE}" >> ${GITHUB_ENV}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_PAT }}
          RELEASE_DATE: ${{ env.RELEASE_DATE }}
          COSIGN_EXPERIMENTAL: 1


