on:
  workflow_call:
    inputs:
      cosign-version:
        required: false
        type: string
        default: 'v1.13.1'
      goprivate:
        required: false
        type: string
        default: go.step.sm,github.com/smallstep
      go-version:
        required: false
        type: string
        default: 'stable'
      os-dependencies:
        required: false
        type: string
    secrets:
      GORELEASER_PAT:
        required: true
      GORELEASER_KEY:
        required: true
      PAT:
        required: false

jobs:
  goreleaser:
    name: Upload Assets To Github w/ goreleaser
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    steps:
      - name: Install Dependencies # Some dependencies require this package
        if: ${{ inputs.os-dependencies != '' }}
        run: |
          sudo apt-get install ${{ inputs.os-dependencies }}
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '${{ inputs.go-version }}'
          check-latest: true
          cache: true
      - name: Reconfigure Git for private repos
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        run: |
          git config --global --add url."https://${{ secrets.PAT }}@github.com/smallstep/".insteadOf https://github.com/smallstep/
          git config --global --add url."https://${{ secrets.PAT }}@github.com/smallstep/".insteadOf git+ssh://git@github.com/smallstep/
      - name: Install cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0
        with:
          cosign-release: '${{ inputs.cosign-version }}'
      - name: Get Release Date
        id: release_date
        run: |
          RELEASE_DATE=$(date -u +"%y-%m-%d")
          echo "RELEASE_DATE=${RELEASE_DATE}" >> "${GITHUB_ENV}"
      - name: Run GoReleaser Pro
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          RELEASE_DATE: ${{ env.RELEASE_DATE }}
          COSIGN_EXPERIMENTAL: 1


