on:
  workflow_call:
    inputs:
      os-dependencies:
        required: false
        type: string
      goprivate:
        required: false
        type: string
        default: go.step.sm,github.com/smallstep
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      PAT:
        required: false

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    steps:
      -
        name: Install Dependencies # Some dependencies require this package
        if: ${{ inputs.os-dependencies != '' }}
        env:
          OS_DEPS: ${{ inputs.os-dependencies }}
        run: |
          sudo apt-get update
          # shellcheck disable=SC2086
          sudo apt-get install ${OS_DEPS}
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      -
        name: Reconfigure Git for go.step.sm
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        run: |
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf git+ssh://git@github.com
          git config --global url.git@github.com:.insteadOf https://github.com/
      -
        name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: 'stable'
          check-latest: true
          cache: true
      -
        name: Setup SSH key for private dependencies
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      -
        name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      -
        name: Run govulncheck
        run: govulncheck ./...
