name: Triage

on:
  workflow_call:
    secrets:
      TRIAGE_PAT:
        required: false
    inputs:
      run-label-pr:
        required: false
        type: boolean
        default: true
      run-add-to-oss-triage-project:
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  label-pr:
    name: Label PR
    if: (inputs.run-label-pr) && (github.event_name == 'pull_request_target')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Label PR
      run: | # plain GitHub API call replaces "gh pr edit"
        gh api --method POST repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels --field 'labels[]=needs triage'

  add-oss-project:
    name: Add to OSS Triage Project
    if: (inputs.run-add-to-oss-triage-project)
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/smallstep/projects/94
          github-token: ${{ secrets.TRIAGE_PAT }}
