name: Triage

on:
  workflow_call:
    secrets:
      TRIAGE_PAT:
        required: false
    inputs:
      run-label-pr:
        required: false
        type: boolean
        default: true
      run-add-to-oss-triage-project:
        required: false
        type: boolean
        default: true

jobs:
  label-pr:
    name: Label PR
    if: (inputs.run-label-pr) && (github.event_name == 'pull_request_target')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Label PR
      run: |
        gh pr edit ${{ github.event.pull_request.number }} --add-label "needs triage"

  add-oss-project:
    name: Add to OSS Triage Project
    if: (inputs.run-add-to-oss-triage-project)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/orgs/smallstep/projects/94
          github-token: ${{ secrets.TRIAGE_PAT }}
